### ISSUE TITLE
pyexiftool tag values different from command line exiftool tag values (print conversion enabled on command line by default)

### ISSUE THREAD

**Issue by abetomas** [sylikc/pyexiftool#42]
I've been using the pyexiftool (v0.5) in a Python3.9 and I've noticed that the returned tag values for QuickTime:MajorBrand is not the same as the command line version of exiftool.  With pyexiftool, QuickTime:MajorBrand returns 'qt', whereas exiftool returns 'Apple QuickTime (.MOV/QT)'.

Sorry if this is the wrong forum to post, I am not sure where to inquire.  Please see attached.

Thanks for your help.  

Abe
[pyexif-tags.txt](https://github.com/sylikc/pyexiftool/files/8281156/pyexif-tags.txt)

**Comment by sylikc** [comment]
Hi!

This is due to the presence of the `-n` flag by default in PyExifTool.  See [ExifTool constructor documentation](https://sylikc.github.io/pyexiftool/reference/1-exiftool.html#exiftool.ExifTool.__init__)

This disables what's called **print conversion**.  It causes raw values to be print out instead of "human readable" ones.  What PyExifTool is dumping out is the actual value of the tag.

If you'd like it to return exactly what you see on the command line, you can initialize with ```exiftool.ExifTool(common_args=None)```

**Comment by sylikc** [comment]
> Sorry if this is the wrong forum to post, I am not sure where to inquire. Please see attached.

and this is totally the right place to post :).  Let me know if you have any more questions.

**Comment by abetomas** [comment]
thanks.

**Comment by sylikc** [comment]
@abetomas I just put this into a summary for the FAQ page.  Let me know if that FAQ page helps, or any comments you might have on the way it's documented https://sylikc.github.io/pyexiftool/faq.html#pyexiftool-output-is-different-from-the-exiftool-command-line

**Comment by abetomas** [comment]
Thanks Kevin.  The FAQ certainly helps… as per the examples provided, it is always good practice to compare expected outputs between the command-line exiftool versus the python wrapper.  

mea culpa … I should have done a more thorough RTFM (Read The Freakin’ Manual) on the documented info available on the pyexiftool site ;>)

Regards.
