### ISSUE TITLE
reading metadata of empty file

### ISSUE THREAD

**Issue by Yang-z** [sylikc/pyexiftool#75]
Use Exiftool in command line to read metadata of a empty file:
```
PS H:\dev\git\ExifToolGUI\.samples\empty file> exiftool -j ./empty.txt
[{
  "SourceFile": "./empty.txt",
  "ExifToolVersion": 12.64,
  "FileName": "empty.txt",
  "Directory": ".",
  "FileSize": "0 bytes",
  "FileModifyDate": "2023:07:17 23:38:56+08:00",
  "FileAccessDate": "2023:07:17 23:38:56+08:00",
  "FileCreateDate": "2023:07:17 23:38:56+08:00",
  "FilePermissions": "-rw-rw-rw-",
  "Error": "File is empty"
}]
```
It returns at least the file system metadata, but pyExiftool returns nothing but throws a error.

**Comment by sylikc** [comment]
This is by design.

Exiftool actually returns an error code to the calling process. And it shows "Error" in the output. It's just that when you run it on the command line, the interpreter ignores that code.

You can disable that error check with `check_execute` property

**Comment by sylikc** [comment]
See here for the [help of ExifToolHelper.check_execute property](https://sylikc.github.io/pyexiftool/reference/2-helper.html#exiftool.ExifToolHelper.check_execute).

It cites exactly that use case... if you scan a whole directory with some invalid files, Exiftool will return an error indicating at least one of the files is bad.  You can use `check_execute` to be `False` and then do manual checks yourself using [ExifTool.last_status](https://sylikc.github.io/pyexiftool/reference/1-exiftool.html#exiftool.ExifTool.last_status)

Since you're doing that GUI, it's highly recommended that you check that `last_status` if you set `check_execute` to False... because some weird errors come up that you could miss if you don't check the code.  I had put in that whole status check because it took me quite awhile to hunt down some obscure problems, which could be caught with just the error code.
